spring.application.name=assistente-pessoal

# Define a porta do projeto, utilizando a 8080 como padrão.
# Importante para execução local e deploy.
server.port=${PORT:8080}


# Banco de dados PostgreSQL - Supabase
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# User Clients
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.webhook.url=${TELEGRAM_WEBHOOK_URL}

#IA
ai.provider=echo


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false


# Actuator
# Configurações do Actuator para monitoramento da aplicação.
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized

# Logging
logging.level.root=INFO
logging.level.com.isaque.assistentepessoal=INFO